version: '3.8'

services:
    node_db:
        container_name: node_cubos_db
        image: 'postgres:12'
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=savio_cubos
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=cubos_db
        volumes:
            - nps_data:/var/lib/postgresql/data

    node_backend:
        container_name: node_cubos_container
        image: node-api-prod:1.0.0
        restart: unless-stopped
        build:
            context: .
            # context: client
            # target: production
            # dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            - EXTERNAL_PORT=3001
            - PGDATABASE=cubos_db
            - PGUSER=savio_cubos
            - PGPASSWORD=12345
            - PGHOST=node_db
        depends_on:
            - node_db

    # react_frontend:
    #     container_name: node_cubos_container
    #     image: react-client-prod:1.0.0
    #     restart: unless-stopped
    #     build:
    #         # context: client
    #         # target: production
    #         # dockerfile: Dockerfile
    #     ports:
    #         - '8080:8081'
    #     depends_on:
    #         - node_backend

volumes:
    nps_data: {}
