version: '3.8'

services:
    node_db:
        container_name: postgres_db
        image: 'postgres:12'
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - nps_data:/var/lib/postgresql/data

    node_backend:
        container_name: node_api
        image: node-api:0.0.2
        build:
            context: .
        ports:
            - ${EXTERNAL_PORT}:3001
        environment:
            EXTERNAL_PORT: ${EXTERNAL_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

        depends_on:
            - node_db

volumes:
    nps_data: {}
